import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { AnalysisReport, CoreThesis } from "@/types/AnalysisReport";
import { Sparkles, TrendingUp, TriangleAlert } from "lucide-react";

interface ExecutiveSummaryProps {
    thesis?: CoreThesis;
    summary?: string;
    metadata?: AnalysisReport['metadata'];
    lang?: string;
}

const verdictMap = {
    positive: {
        labelEn: "Positive",
        labelZh: "积极",
        className: "border-emerald-500/30 bg-emerald-500/10 text-emerald-300",
    },
    mixed: {
        labelEn: "Mixed",
        labelZh: "中性偏谨慎",
        className: "border-amber-500/30 bg-amber-500/10 text-amber-300",
    },
    negative: {
        labelEn: "Negative",
        labelZh: "偏空",
        className: "border-red-500/30 bg-red-500/10 text-red-300",
    },
} as const;

function splitFallbackSummary(summary?: string): string[] {
    if (!summary) return [];
    return summary
        .split(/(?<=[。！？.!?])\s*/)
        .map((sentence) => sentence.trim())
        .filter(Boolean);
}

export function ExecutiveSummary({ thesis, summary, metadata, lang = 'en' }: ExecutiveSummaryProps) {
    const isZh = lang === 'zh';
    const keyPoints = thesis?.keyPoints?.filter(Boolean) ?? [];
    const watchItems = thesis?.watchItems?.filter(Boolean) ?? [];
    const supportingEvidence = thesis?.supportingEvidence?.filter((item) => item?.detail) ?? [];
    const fallbackSentences = keyPoints.length > 0 ? [] : splitFallbackSummary(thesis?.summary || summary);
    const verdict = thesis?.verdict && thesis.verdict in verdictMap
        ? verdictMap[thesis.verdict as keyof typeof verdictMap]
        : verdictMap.mixed;

    return (
        <Card className="overflow-hidden border-slate-800 bg-slate-900/70 backdrop-blur-sm">
            <div className="grid grid-cols-1 lg:grid-cols-[300px,1fr]">
                <div className="border-b border-slate-800 bg-[radial-gradient(circle_at_top,_rgba(16,185,129,0.18),_transparent_55%),linear-gradient(180deg,_rgba(15,23,42,0.98),_rgba(2,6,23,0.98))] p-6 lg:border-b-0 lg:border-r">
                    <div className="flex h-full flex-col justify-between gap-6">
                        <div className="space-y-4">
                            <div className="flex items-center gap-2 text-emerald-300">
                                <Sparkles className="h-5 w-5" />
                                <span className="text-sm font-semibold uppercase tracking-[0.25em]">
                                    {isZh ? '核心分析' : 'Core Thesis'}
                                </span>
                            </div>
                            <div className="flex flex-wrap gap-2">
                                <Badge variant="outline" className={verdict.className}>
                                    {isZh ? verdict.labelZh : verdict.labelEn}
                                </Badge>
                                <Badge variant="outline" className="border-slate-700 bg-slate-950/70 text-slate-300">
                                    {isZh ? '研究视角' : 'Research Note'}
                                </Badge>
                            </div>
                        </div>

                        <div className="space-y-4">
                            <h2 className="text-3xl font-bold leading-tight text-white">
                                {thesis?.headline || (isZh ? '等待模型形成核心判断…' : 'Waiting for the model to form a clear thesis...')}
                            </h2>
                            <p className="text-sm leading-7 text-slate-300">
                                {thesis?.summary || summary || (isZh ? '正在生成结构化分析内容。' : 'Structured analysis is being generated.')}
                            </p>
                        </div>

                        {metadata && (
                            <p className="text-xs text-slate-500">
                                {isZh
                                    ? `由 ${metadata.modelName} 生成于 ${new Date(metadata.generatedAt).toLocaleString('zh-CN')} (${metadata.language === 'zh' ? '中文' : metadata.language})`
                                    : `Generated by ${metadata.modelName} at ${new Date(metadata.generatedAt).toLocaleString()} (${metadata.language})`}
                            </p>
                        )}
                    </div>
                </div>

                <CardContent className="space-y-6 p-6">
                    <section className="space-y-3">
                        <div className="flex items-center gap-2 text-emerald-300">
                            <TrendingUp className="h-4 w-4" />
                            <h3 className="text-sm font-semibold uppercase tracking-[0.25em]">
                                {isZh ? '关键信号' : 'Key Signals'}
                            </h3>
                        </div>
                        <div className="grid gap-3 md:grid-cols-2">
                            {(keyPoints.length > 0 ? keyPoints : fallbackSentences).map((point, index) => (
                                <div key={`${point}-${index}`} className="rounded-xl border border-slate-800 bg-slate-950/60 p-4">
                                    <p className="text-sm leading-7 text-slate-200">{point}</p>
                                </div>
                            ))}
                        </div>
                    </section>

                    {supportingEvidence.length > 0 && (
                        <section className="space-y-3">
                            <div className="flex items-center gap-2 text-emerald-300">
                                <Sparkles className="h-4 w-4" />
                                <h3 className="text-sm font-semibold uppercase tracking-[0.25em]">
                                    {isZh ? '论据支撑' : 'Evidence Stack'}
                                </h3>
                            </div>
                            <div className="grid gap-3">
                                {supportingEvidence.map((item, index) => (
                                    <div key={`${item.label}-${index}`} className="rounded-xl border border-slate-800 bg-slate-950/40 p-4">
                                        <p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400/80">
                                            {item.label}
                                        </p>
                                        <p className="text-sm leading-7 text-slate-300">{item.detail}</p>
                                    </div>
                                ))}
                            </div>
                        </section>
                    )}

                    {watchItems.length > 0 && (
                        <section className="space-y-3">
                            <div className="flex items-center gap-2 text-amber-300">
                                <TriangleAlert className="h-4 w-4" />
                                <h3 className="text-sm font-semibold uppercase tracking-[0.25em]">
                                    {isZh ? '后续跟踪' : 'Watch Items'}
                                </h3>
                            </div>
                            <div className="space-y-2">
                                {watchItems.map((item, index) => (
                                    <div key={`${item}-${index}`} className="rounded-xl border border-amber-500/15 bg-amber-500/5 px-4 py-3 text-sm leading-7 text-slate-300">
                                        {item}
                                    </div>
                                ))}
                            </div>
                        </section>
                    )}
                </CardContent>
            </div>
        </Card>
    );
}
