import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AnalysisReport } from "@/types/AnalysisReport";

interface ExecutiveSummaryProps {
    summary: string;
    metadata: AnalysisReport['metadata'];
}

export function ExecutiveSummary({ summary, metadata }: ExecutiveSummaryProps) {
    return (
        <Card className="bg-slate-900 border-slate-800">
            <CardHeader className="border-b border-slate-800">
                <CardTitle className="text-emerald-400">📊 Executive Summary</CardTitle>
            </CardHeader>
            <CardContent className="p-6">
                <p className="text-slate-300 text-lg leading-relaxed">{summary}</p>
                <p className="text-slate-500 text-xs mt-4">
                    Generated by {metadata.modelName} at {new Date(metadata.generatedAt).toLocaleString()} ({metadata.language})
                </p>
            </CardContent>
        </Card>
    );
}
